### ISSUE TITLE
Create Escrow Form Component In Web

### ISSUE THREAD

**Issue by DiegoB1911** [Crypto-Jaguars/Revolutionary_Farmers#14]
## Description

We need to implement the "Create Escrow" form as a component in our Next.js project. The form allows users to fill in details to set up an escrow agreement and should follow the design specified in the provided UI.

## 1. **Reusable Component**: 
   - Create a Next.js functional component named `EscrowForm`.
   - The component should accept props for dynamic behavior (e.g., onSubmit, default values).

## 2. **Form Fields**: 
   Include the following input fields:
   - **Engagement**: Text input for engagement details.
   - **Description**: Text input for a description.
   - **Service Provider**: Text input for entering the wallet of the service provider.
   - **Amount**: Text input for the amount/price of the escrow.

## 3. **Validation**:
   - Add basic client-side validation (e.g., required fields, wallet address format, numeric validation for the amount).

## 4. **Styling**:
   - Match the design in the provided screenshot, including colors, fonts, and layout.
   - Ensure responsiveness for various screen sizes.

## 5. **Submit Button**:
   - Include a button labeled **"Create escrow"**.
   - Trigger the `onSubmit` prop or handle the form submission.

## Mockups / References
![image](https://github.com/user-attachments/assets/cdf5f16d-7aec-4da4-934f-9f0f5846f744)

## Refer to the figma design:  
[FIGMA DESIGN](https://www.figma.com/design/okdNMG3dW4UFcKUSikrs6e/Revolutionary-Farmers?node-id=7-2&node-type=canvas&t=M2XbI5NKqSvBUI8P-0)

## Milestones
- [ ] Create the `EscrowForm` component.
- [ ] Add input fields.
- [ ] Apply styling to match the design.

**Comment by raizo07** [comment]
Mind if I take this issue?

**Comment by abdegenius** [comment]
Can I take this issue?I can comfortably handle this issues

**Comment by KevinLatino** [comment]
Hello @DiegoB1911! My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will create a reusable EscrowForm component in Next.js with fields for "Engagement," "Description," "Service Provider," and "Amount," including client-side validation for required fields, wallet format, and numeric input. The design will match the UI provided, be responsive, and include a "Create Escrow" button to trigger submission dynamically through props.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

## How I Would Resolve This

To implement the "Create Escrow" form as specified in the design and requirements, I will follow these steps:

---

### 1. **Create the Reusable Component**
   - Define a functional component named `EscrowForm` in Next.js.
   - The component will accept props such as:
     - `onSubmit` for handling form submission.
     - `defaultValues` for pre-filling the form fields when necessary.

---

### 2. **Form Fields**
   - Include the following input fields:
     - **Engagement**: Text input for engagement details.
     - **Description**: Text input for a description.
     - **Service Provider**: Text input for entering the wallet address.
     - **Amount**: Text input for the numeric amount.
   - Add placeholders matching the UI design for each field.

---

### 3. **Validation**
   - Implement basic client-side validation:
     - Ensure all fields are required.
     - Validate that the service provider input follows wallet address format (e.g., alphanumeric or specific patterns).
     - Validate that the amount input is numeric.

   Example validation logic:
   ```javascript
   const validateForm = (data) => {
     const errors = {};
     if (!data.engagement) errors.engagement = "Engagement is required.";
     if (!data.description) errors.description = "Description is required.";
     if (!data.serviceProvider) errors.serviceProvider = "Service provider wallet is required.";
     if (!/^[0-9]+(\.[0-9]+)?$/.test(data.amount)) errors.amount = "Amount must be a valid number.";
     return errors;
   };
   ```

---

### 4. **Styling**
   - Match the provided screenshot design using Tailwind CSS or custom CSS.
   - Include the following styles:
     - **Gradient Background**: Use a linear gradient matching the screenshot.
     - **Input Fields**:
       - Rounded borders with light gray backgrounds.
       - Subtle focus states (e.g., border color change on focus).
     - **Button**:
       - Rounded with a white background and hover effect.
   - Responsive Design:
     - Use media queries or utility classes to ensure the form renders well on all screen sizes.

---

### 5. **Submit Button**
   - Label the button as "Create escrow."
   - Trigger the `onSubmit` prop or handle form submission locally.
   - Prevent the default form action and log form data on submission for testing.

---

### 6. **Implementation Example**
   Example JSX Component:
   ```jsx
   import { useState } from "react";

   const EscrowForm = ({ onSubmit, defaultValues = {} }) => {
     const [formData, setFormData] = useState({
       engagement: defaultValues.engagement || "",
       description: defaultValues.description || "",
       serviceProvider: defaultValues.serviceProvider || "",
       amount: defaultValues.amount || "",
     });

     const handleChange = (e) => {
       setFormData({ ...formData, [e.target.name]: e.target.value });
     };

     const handleSubmit = (e) => {
       e.preventDefault();
       const errors = validateForm(formData);
       if (Object.keys(errors).length === 0) {
         onSubmit(formData);
       } else {
         console.log("Validation Errors:", errors);
       }
     };

     return (
       <form onSubmit={handleSubmit} className="bg-gradient-to-b from-green-500 to-blue-700 p-6 rounded-md max-w-md mx-auto">
         <h2 className="text-2xl font-bold text-white">Create Escrow</h2>
         <p className="text-sm text-gray-200 mb-4">Fill in the details below to set up a secure and reliable escrow agreement.</p>

         <label className="block text-gray-200">Engagement</label>
         <input
           type="text"
           name="engagement"
           value={formData.engagement}
           onChange={handleChange}
           placeholder="Enter the engagement"
           className="w-full p-2 mb-4 border rounded-md"
         />

         <label className="block text-gray-200">Description</label>
         <input
           type="text"
           name="description"
           value={formData.description}
           onChange={handleChange}
           placeholder="Enter description"
           className="w-full p-2 mb-4 border rounded-md"
         />

         <label className="block text-gray-200">Service Provider</label>
         <input
           type="text"
           name="serviceProvider"
           value={formData.serviceProvider}
           onChange={handleChange}
           placeholder="Enter the service provider"
           className="w-full p-2 mb-4 border rounded-md"
         />

         <label className="block text-gray-200">Amount</label>
         <input
           type="text"
           name="amount"
           value={formData.amount}
           onChange={handleChange}
           placeholder="Please enter the amount/price of the escrow"
           className="w-full p-2 mb-4 border rounded-md"
         />

         <button
           type="submit"
           className="bg-white text-black py-2 px-4 rounded-md hover:bg-gray-200"
         >
           Create escrow
         </button>
       </form>
     );
   };

   export default EscrowForm;
   ```

---

### 7. **Testing**
   - Ensure the component renders correctly with and without default values.
   - Validate responsiveness across screen sizes.
   - Test all form fields and submission behavior.
   - Ensure styling matches the provided design.

---

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by mimisavage** [comment]
Could I take over this issue?

**Comment by 0xdevcollins** [comment]
Could I be assigned to this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

**Comment by Ayoazeez26** [comment]
I'd be happy to do this. I would make the form a component and also have the validation for the form inputs. I would ensure it works as expected before submitting a PR
ETA - 2 days

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

I will create a reusable EscrowForm component in Next.js with dynamic props like onSubmit. It will include inputs for engagement, description, service provider wallet, and amount, with client-side validation and responsive styling matching the Figma design. A "Create escrow" button will handle submission, ensuring a clean, user-friendly implementation.

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would follow all the guidelines and instructions to get exactly what you want.
Pls feel free to reach out!

**Comment by ShantelPeters** [comment]
Is it okay if I tackle this?

**Comment by myspace20** [comment]
I can handle this issue using shadcn, zod and react hook form while adhering to responsive design and by using a form wrapper that accepts props to allow for custom behavior. I have over 2+ years of experience as a developer by the way.

**Comment by armandocodecr** [comment]
Hello, this is Armando from the Dojo. Could you take this issue?
I have more than 2 years of experience with Next.js technology, since I started I've been involved in the frontend area, so I feel fully qualified to solve this issue.

I propose to use 2 libraries that allow you to create fully customizable forms with their respective validations in a very simple way. These 2 libraries would be: “Yup” and “Formik”.

I hope you like the proposal.

**Comment by juandiegocv27** [comment]
Hi, I´m Juan Diego Carballo, a full-stack developer specializing in React and Next.js. I contributed in many web3 project via OnlyDust, the majority in react, so I would love to create ths form for this amazing project and help the efficiency for the final product. Could I grab this task?

**Comment by DiegoB1911** [comment]
All yours, @JosueBrenes

**Comment by Bran18** [comment]
Hello there. I’m Brandon, part of the ⛩️ Dojo Coding community, and I would love to contribute to this project! 🚀  This might be my first contribution here.

I've done quite a few forms in our apps, feel free to check out the one from MB (https://masterbots.ai/) as one example xD. I would love to help out with creating the one you need and adding all the elements it needs. I will be following the strategy we use in our products.

* Create reusable component
* Create util for reusable logic validations
* User friendly place holder
* Accessibility based component elements
* Any other cool stuff and easy to maintain 

Lmk if I can start working on it.  Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18.

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly.I’ll create a reusable EscrowForm component in Next.js that accepts props like onSubmit and defaultValues for flexibility. The form will include fields for Engagement, Description, Service Provider, and Amount with basic validation, ensuring required fields, proper wallet format, and numeric validation for the amount.

For styling, I’ll match the design using CSS modules or Tailwind CSS, making it responsive across screen sizes. The form will have a "Create Escrow" button that triggers the form submission. This approach ensures the form is functional, reusable, and integrates smoothly with the app. I would really love to be assigned this issue and work on this project.
