### ISSUE TITLE
Update Landing Page and Background to Match Figma Design

### ISSUE THREAD

**Issue by DiegoB1911** [Crypto-Jaguars/Revolutionary_Farmers#15]
## Description

Update the current landing page and background to match the design provided in the Figma reference. This includes ensuring the styles, layout, and visual elements are consistent with the Figma design in terms of colors, typography, spacing, and overall layout.

## 1. **Update Background**:
   - Replace the current background with the one shown in the Figma design.
   - Ensure the gradient, abstract shapes, or textures match the provided image.

## 2. **Typography**:
   - Update the **"Revolutionary Farmers"** title to match the font style, size, and color in the design (green and bold).
   - Update the subtitle text to match the font and spacing from the design.

## 3. **Navigation Bar**:
   - Ensure the **"Create Escrow"** and **"Claim Escrow Earnings"** links match the font, size, color, and alignment in the Figma design.
   - Update the **"Disconnect"** button to match the design, including any hover effects or colors.

## 4. **Logo Placement**:
   - Adjust the placement of the logo in the top-left corner to match the spacing and size in the Figma design.

## 6. **Styling Consistency**:
   - Match all colors, padding, margins, and layout spacing with the Figma design.
   - Verify font-family and sizes are consistent with the design specifications.

## Mockups / References
![image](https://github.com/user-attachments/assets/3cfbcb68-c113-4723-92d2-96e08f2c9faf)

## Refer to the figma design for reference:  
[FIGMA DESIGN](https://www.figma.com/design/okdNMG3dW4UFcKUSikrs6e/Revolutionary-Farmers?node-id=7-7212&node-type=frame&t=2Z4RmEPkGWYzsDps-0)

## Milestones
- [ ] Update background styles and layout.  
- [ ] Update typography and text alignment.  
- [ ] Adjust navigation bar links and button styles.  
- [ ] Ensure responsiveness and styling consistency.

**Comment by Iwueseiter** [comment]
Can I be assigned to this?
I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.

**Comment by abdegenius** [comment]
Is it okay if I tackle this? I can comfortably handle this issues

**Comment by KevinLatino** [comment]
Hello @DiegoB1911! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will update the landing page and background to match the Figma design, ensuring accurate gradients, typography, and layout. This includes aligning the title, subtitle, navigation links, "Disconnect" button, and logo placement with the design. I’ll also ensure consistent colors, spacing, and styling across the page.
I have made landing pages such as this one: https://buildmyevent.xyz/

**Comment by mimisavage** [comment]
I'd love to give this a go.

**Comment by Akshola00** [comment]
I'd like to handle this task.

**Comment by qgatssdev** [comment]
I'm a fullstack engineer with over 4 years of experience. The ETA for this is one day.

**Comment by 0xdevcollins** [comment]
Is it okay if I take this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

**Comment by Villarley** [comment]
hi @DiegoB1911 🚀🚀
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon(By BaseLatam) for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would tackle the issue by following all the steps you added in the instructions, and getting it ready the faster possible. I would love to contribute because I have a huge background in tailwindCSS, and frontend in general.
Feel free to reach out!

**Comment by caxtonacollins** [comment]
i will love to be assigned this issue. please assign me

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by od-hunter** [comment]
I am a blockchain developer, and my experience includes html, css, react, javaScript, typescript, solidity and cairo.

To solve this issue I’ll take the following steps:
1.⁠ ⁠I’ll implement background using linear-gradient or background-image, also background-size, background-repeat, and background-position for layout accuracy.
2.⁠ ⁠⁠I’ll style the title and subtitle using TailwindCSS. I’ll apply font-family, font-size, font-weight, and color to match the Figma specification and also ensure proper line-height and spacing consistency with Figma design.
3.⁠ ⁠⁠I’ll use React components for links and buttons with Tailwind utility classes for styles, and manage alignment and spacing with flexbox 
4.⁠ ⁠I’ll adjust placement using CSS properties like position, top, left, padding, and margin and make sure my scaling is consistent.
5.⁠ ⁠⁠I’ll ensure responsiveness and also test to see that changes have been implemented.

Please assign me I’m ready to work.

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would follow all the guidelines and instructions to get exactly what you want.
Pls feel free to reach out!

**Comment by SudiptaPaul-31** [comment]
Would love to tackle this!

My approach:

Replacing the current background with the gradient/texture from the Figma design and ensure it scales properly.
Update "Revolutionary Farmers" and styles to match the Figma reference.
Style links and "Disconnect" button per the Figma design, including hover effects.
And at last adjusting the logo size

ETA-1day

**Comment by evgongora** [comment]
My background and how it can be leveraged:
Hello! My name is Erick, I'm part of the Dojo Coding community.
I'm a software engineering student working on fullstack web development, I have experience building different views with responsive layout using Next.js/TS/React.
I have experience as a contributor and as a maintainer.
You can check my work here:  https://app.onlydust.com/u/evgongora

How I will Implement this:

1. Background & Layout
I'll start with globals.css and layout.tsx to implement the base styles:

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-5`}
      >
        <Header />
        {children}
        <footer></footer>
        <Toaster />
      </body>
    </html>
  );
}

Add background patterns and colors in:

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;
    --card: 0 0% 100%;
    --card-foreground: 240 10% 3.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 240 10% 3.9%;
    --primary: 240 5.9% 10%;
    --primary-foreground: 0 0% 98%;
    --secondary: 240 4.8% 95.9%;
    --secondary-foreground: 240 5.9% 10%;
    --muted: 240 4.8% 95.9%;
    --muted-foreground: 240 3.8% 46.1%;
    --accent: 240 4.8% 95.9%;
    --accent-foreground: 240 5.9% 10%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 98%;
    --border: 240 5.9% 90%;
    --input: 240 5.9% 90%;
    --ring: 240 10% 3.9%;
    --chart-1: 12 76% 61%;
    --chart-2: 173 58% 39%;
    --chart-3: 197 37% 24%;
    --chart-4: 43 74% 66%;
    --chart-5: 27 87% 67%;
    --radius: 0.5rem;
  }
  .dark {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --card: 240 10% 3.9%;
    --card-foreground: 0 0% 98%;
    --popover: 240 10% 3.9%;
    --popover-foreground: 0 0% 98%;
    --primary: 0 0% 98%;
    --primary-foreground: 240 5.9% 10%;
    --secondary: 240 3.7% 15.9%;
    --secondary-foreground: 0 0% 98%;
    --muted: 240 3.7% 15.9%;
    --muted-foreground: 240 5% 64.9%;
    --accent: 240 3.7% 15.9%;
    --accent-foreground: 0 0% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 0 0% 98%;
    --border: 240 3.7% 15.9%;
    --input: 240 3.7% 15.9%;
    --ring: 240 4.9% 83.9%;
    --chart-1: 220 70% 50%;
    --chart-2: 160 60% 45%;
    --chart-3: 30 80% 55%;
    --chart-4: 280 65% 60%;
    --chart-5: 340 75% 55%;
  }
}

2. Typography & Content
Update the main page content in page.tsx:
export default function Home() {
  return (
    <Bounded center={true}>
      <div className="flex flex-col md:flex-row justify-center items-center w-full h-full mt-0 md:mt-20 gap-10">
        <h1 className="text-5xl md:text-6xl font-bold">
          Revolutionary Farmers
        </h1>
        <hr className="hidden md:block bg-gray-200 w-0.5 h-96" />
        <p className="text-xl">
          <strong>Escrows</strong> for the field of <strong>agriculture</strong>, <br />
          and with the objective of <strong>benefiting farmers</strong> <br />
          as well as the buyers of the products grown.
        </p>
      </div>
    </Bounded>
  );
}

3. Navigation & Header (2-3 hours)
Modify header styles and components in Header.tsx:

  return (
    <header className="flex flex-col md:flex-row w-full justify-between gap-5 container mx-auto">
      <Link href="/" className="mx-auto md:m-0">
        {" "}
        <Image src="/logo.jpeg" width={100} height={100} alt="logo" />
      </Link>

      {/* Navigation Menu */}
      <ItemsHeader isEnabled={address} />

      {/* Wallet and Theme Toggle */}
      <div className="flex mx-auto md:m-0 items-center gap-5">
        <ThemeToggle />
        {address ? (
          <>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger>
                  <FaUserCircle size={30} />
                </TooltipTrigger>
                <TooltipContent>
                  <p className="text-base">
                    {address && name + " - " + address}
                  </p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <button
              type="button"
              onClick={handleDisconnect}
              className="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-3 text-center"
            >
              Disconnect
            </button>
          </>
        ) : (
          <button
            type="button"
            onClick={handleConnect}
            className="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-3 text-center"
          >
            Connect
          </button>
        )}
      </div>

Development Process:
- Start with background and layout changes
- Implement typography updates
- Update navigation components
- Add responsive styles
- Test across devices
- Final QA and adjustments

ETA 1-2 days.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by MullerTheScientist** [comment]
hello would love to please address this

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. To update the landing page, I’ll start by replacing the background to match the Figma design, making sure the gradient and textures align perfectly. I’ll update the typography, adjusting the "Revolutionary Farmers" title and subtitle to match the font, size, and spacing. For the navigation, I’ll ensure the links and "Disconnect" button match the design in terms of font, color, and hover effects. I’ll also reposition the logo to match the design’s spacing and size. Lastly, I’ll ensure all styles, like colors, margins, and fonts, are consistent with the Figma design. I would really love to be assigned this issue and work on this project.

**Comment by brolag** [comment]
Hi, I'd love to work on this issue. I have more than 10 years of experience working with web technologies.

My plan:

- Get the assets from the figma file.
- Set the correct typography.
- Create the necessary typography and button components.
- Create an amazing moving background ;)
- Ensure everything is responsive

**Comment by Ugo-X** [comment]
@DiegoB1911 Thank you, will get to work.
